apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: sample-server-deployment
spec:
    replicas: 4
    template:
        metadata:
            labels:
                app: sample-server
        spec:
            containers:
            - name: sample-server
              image: gcr.io/propane-folio-103015/sample-server:0.0.5
              ports:
              - containerPort: 8080
              env:
              - name: PORT
                value: "8080"
