kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: task-pv-claim
spec:
    storageClassName: ""
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 3Gi
